<?php get_header(); ?>
<div class="post container">
  <h1 class="mb-4">Important Mortgage Notices</h1>
  <h2>About Homebuyer</h2>
  <p>Homebuyer.com is a public resource, open to everyone. There is no cost for using our website. We don't charge for reading our articles, watching our videos, interacting with our tools, or personalizing a home buyer experience. We don't charge for live chat, we don't charge for advice, and when you're ready to get pre-approved for your mortgage or make a formal loan application - should you allow us to help you! - we don't charge for that service, either.Why do we give away so much? Because we believe that mortgage lenders serve at their customers' pleasure, and the best way to earn a home buyer's trust and business is to give away as much as we can and be as helpful as humanly possible. These are our values and we live them every day. We recognize that, after you've found a home, you might want to give your business to somebody else. That's okay with us. There will be no hard feelings. Yes, we want your business. Of course we do! But, we judge ourselves based on how well we serve and, ultimately, we want you to be satisfied with your Homebuyer.com experience.</p>
  <h2>Mortgage Disclosures</h2>
  <p>Homebuyer.com is a website that provides information about mortgages and consumer financial products. This site is for informational purposes only. This site is not an advertisement for products. The views and opinions expressed herein are those of the respective authors and do not reflect the policy or position of Homebuyer.com, its officers, parent, or affiliates. We directly offer mortgages and consumer financial products through Novus Home Mortgage, a division of Ixonia Bank. We are not affiliated with the US Government, US Armed Forces, or Department of Veteran Affairs. If you would like to find out more information about your veteran benefits, please visit the Official US Government website for the Department of Veteran Affairs, or the US Department of Housing and Urban Development. US Government agencies have not reviewed this information, and this site is not connected with any government agency. Please contact us if you are suspicious of fraudulent activities, or have any questions. Homebuyer.com is operated by Novus Home Mortgage, a division of Ixonia Bank, NMLS #423065.</p>
  <h2>Agreement to Calls and Information Sharing</h2>
  <p>If you submit to Homebuyer.com through this website or otherwise you are making an inquiry as to lending programs and services offered by Novus Home Mortgage. You understand and agree that if you submit an inquiry, we may share the information that you provide, including, but not limited to, your full name, birth date, address, telephone number, and social security number with Novus Home Mortgage so that they may respond to your inquiry. You authorize Homebuyer.com to share your information, either as provided by you or as corrected by us. You understand that requirements for a particular product or service, including a mortgage, are determined by Novus Home Mortgage. Nothing on this website constitutes an offer for a loan commitment or interest rate lock agreement.</p>

  <p>By submitting your contact request for a loan product, you are consenting to be contacted by Novus Home Mortgage, even if you have opted in to the National Do Not Call List, any state equivalent Do Not Call List or the internal Do Not Call List of any company. You understand that Novus Home Mortgage may maintain the information you submitted to us even if you decide not to use their services. In the event you no longer want to receive communications from Novus Home Mortgage, you agree to notify the them directly. You can opt-out of various contact methods here: <a href="https://www.novushomemortgage.com/contact/" target="_blank" rel="nofollow noopener">https://www.novushomemortgage.com/contact/</a></p>
  <h2>Disclosure</h2>
  <p>Novus Home Mortgage, a division of Ixonia Bank is an Equal Housing Lender. As prohibited by federal law, we do not engage in business practices that discriminate on the basis of race, color, religion, national origin, sex, marital status, age (provided you have the capacity to enter into a binding contract), because all or part of your income may be derived from any public assistance program, or because you have, in good faith, exercised any right under the Consumer Credit Protection Act. The federal agency that administers our compliance with these federal laws is the FDIC Consumer Response Center 1100 Walnut Street Box #11 Kansas City, MO 64106 877-275-3342.</p>
  <h2>Privacy and Security</h2>
  <p>For information on how Novus Home Mortgage uses and protects the personal information that you may provide through this application, please visit: <a href="https://www.novushomemortgage.com/privacy/" target="_blank" rel="nofollow noopener">https://www.novushomemortgage.com/privacy/</a>.</p>
</div>
<?php
  $args = [ 'slug' => get_queried_object()->post_name ];
  get_footer(null, $args);
?>
